store token position
mblink/htmldiff.js pull request #2
Opened 2021-05-06 12:42 UTC by milahu

this is useful for a "live diff" editor, where i must reset the cursor position

[WIP demo](https://codesandbox.io/s/htmldiffjs-live-diff-demo-work-in-progress-rneyc?file=/src/index.js)

2021-12-22 16:05 UTC, jleider commented
Hi @milahu, apologies for the delayed response. We are taking a look at your PR today. Do you think you could add some tests specifically for the tokenizer changes you made?

2021-12-22 16:38 UTC, SuttonKyle requested changes
Makes sense, for the most part. Changes are not particularly relevant to our use cases -- @jleider do you think it's worth including this added functionality in the main repo or should this PR really be another fork?

2021-12-22 16:38 UTC, SuttonKyle commented on src/htmldiff.ts
> +  for (let charIdx = 0; charIdx < unicodeChars.length; charIdx++) {
```suggestion
  unicodeChars.forEach((char, charIdx) => {
```

2021-12-22 16:38 UTC, SuttonKyle commented on src/htmldiff.ts
> +          currentWord = '';
why are we removing `char` here?

2021-12-22 16:38 UTC, SuttonKyle commented on src/htmldiff.ts
> +    const char = unicodeChars[charIdx] as string;
```suggestion
```

2021-12-22 16:38 UTC, SuttonKyle commented on src/htmldiff.ts
>      }
You'll have to account for the `style_tag` case as well now.

2021-12-22 18:21 UTC, milahu commented
sorry, i have to abandon this patch

notes:

* `for (var i = 0; ...)` is fastest loop in all environments, `forEach` can have function call overhead
* today i would try to avoid converting string to array

i cannot reproduce why i added `Array.from(html)` to loop unicode chars

```js
for (var c of '\u00e4\u00f6\u00fc') console.log(c)
for (var c of Array.from('\u00e4\u00f6\u00fc')) console.log(c)
// nodejs:
/*
ä
ö
ü
*/
```

more micro optimization: maybe the string parsing could be optimized by looping bytes (Uint8Array typed array), using a jump table to handle values <= 127, and treating all values >= 128 as word chars (all unicode bytes have value >= 128)

2022-01-19 16:34 UTC, jleider commented
Closing this in favor of #3 which incorporates some of these changes.

2022-01-19 16:34 UTC, closed without merging